application: testcss
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /stylesheets
  static_dir: stylesheets

- url: /single
  script: handlers.single.app

- url: /add
  script: handlers.add.app

- url: ./*
  script: handlers.main.app



libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "latest"

